import React,{useEffect,useState}from'react';
import{analyticsConsent,captureTelemetry,setAnalyticsConsent,telemetryAvailable}from'./telemetry';
const sample=`old_url,new_url,status
https://example.com/services,https://example.com/services-new,301
https://example.com/services-new,https://example.com/solutions,301
https://example.com/about,https://example.com/company,301
https://example.com/about,https://example.com/team,301
https://example.com/loop-a,https://example.com/loop-b,301
https://example.com/loop-b,https://example.com/loop-a,301
https://example.com/contact,https://example.com/get-in-touch,301
https://example.com/contact,https://example.com/get-in-touch,301
https://example.com/same,https://example.com/same,301`;
const sampleInventory='https://example.com/services\nhttps://example.com/about\nhttps://example.com/forgotten';
type Report={summary:{inputRows:number;validRows:number;errors:number;warnings:number;exportRows:number;inventoryUrls:number};issues:{row:number;severity:string;code:string;oldUrl:string;message:string}[];reviewedCsv:string;issuesCsv:string;limitations:string[]};
export default function App(){
 const[csv,setCsv]=useState(''),[inventory,setInventory]=useState(''),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reviewed,setReviewed]=useState(false),[filter,setFilter]=useState('all'),[billing,setBilling]=useState(false),[paid,setPaid]=useState(false),[expiry,setExpiry]=useState(''),[saveDraft,setSaveDraft]=useState(false),[consent,setConsent]=useState<'granted'|'denied'|'unset'>('unset');
 useEffect(()=>{
  setConsent(analyticsConsent());
  fetch('/api/config').then(r=>r.ok?r.json():Promise.reject()).then(d=>setBilling(d.billingEnabled)).catch(()=>setNotice('API may be waking up. You can prepare your input and try again.'));
  const params=new URLSearchParams(location.search);
  if(params.has('checkout')){try{const draft=JSON.parse(sessionStorage.getItem('rp:draft')||'null');if(draft){setCsv(draft.csv);setInventory(draft.inventory);setSaveDraft(true);}}catch{}if(params.get('checkout')==='cancelled')setNotice('Checkout cancelled. Your free reports remain available.');else setNotice('Checking your test payment…');history.replaceState({},'',location.pathname);}
  let disposed=false;let attempts=0;let timer:ReturnType<typeof setTimeout>;
  async function status(){try{const r=await fetch('/api/billing/status');const d=await r.json();if(disposed)return;if(d.entitled){setPaid(true);setExpiry(d.expiresAt);if(params.get('checkout')==='success')setNotice('Test project pass active. Rerun your map to use the higher limit.');}else if(params.get('checkout')==='success'&&++attempts<8){timer=setTimeout(status,2000);}else if(params.get('checkout')==='success')setNotice('Payment is not confirmed yet. Reload to check again. Free reports remain available.');}catch{if(!disposed&&params.get('checkout')==='success')setNotice('Payment status unavailable. Reload to retry; no paid access assumed.');}}
  void status();return()=>{disposed=true;clearTimeout(timer);};
 },[]);
 function invalidate(){setReport(null);setReviewed(false);setError('');}
 async function loadFile(file:File|undefined){if(!file)return;if(file.size>1_500_000){setError('CSV exceeds 1.5 MB.');return;}setCsv(await file.text());invalidate();}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setReport(null);setReviewed(false);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csv,inventory})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not analyze this map.');setReport(d);void captureTelemetry('task_succeeded');}catch(e){setError(e instanceof Error?e.message:'Could not reach the API. Try again.');void captureTelemetry('task_failed');}finally{setBusy(false);}}
 async function checkout(){setBusy(true);setError('');try{if(saveDraft)sessionStorage.setItem('rp:draft',JSON.stringify({csv,inventory}));else sessionStorage.removeItem('rp:draft');const r=await fetch('/api/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Test checkout unavailable.');if(d.entitled){setPaid(true);setNotice('Your test pass is already active.');return;}const u=new URL(d.url);if(u.protocol!=='https:'||u.hostname!=='checkout.stripe.com')throw new Error('Unexpected checkout destination.');location.assign(u.href);}catch(e){setError(e instanceof Error?e.message:'Test checkout unavailable.');}finally{setBusy(false);}}
 function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function clear(){setCsv('');setInventory('');invalidate();setNotice('Inputs and report cleared.');sessionStorage.removeItem('rp:draft');}
 const visible=report?.issues.filter(i=>filter==='all'||i.severity===filter)||[];
 return <main>
  <nav><a className="brand" href="/" aria-label="Redirect Preflight home"><span className="mark">↳</span> Redirect Preflight</a><span className="nav-note">A Nex2i experiment <span className="test-badge">TEST MODE</span></span></nav>
  <section className="hero"><div><p className="eyebrow">BEFORE THE MIGRATION. BEFORE THE SURPRISES.</p><h1>Check your redirect map.<br/>Catch <em>migration surprises.</em></h1><p className="lead">Find conflicts, loops and gaps in your proposed URL map. Get a clear review list before your developer configures staging.</p><p className="hint"><a href="/redirect-map-checklist/">Website migration redirect checklist &amp; CSV template →</a></p><div className="pills"><span>↳ No crawler setup</span><span>✓ Explainable checks</span><span>↓ CSV handoff</span></div></div><aside className="scope"><span className="scope-label">THE JOB, IN THREE STEPS</span><ol><li><b>Bring your map</b><span>Old URL → new URL, plus status.</span></li><li><b>Review the exceptions</b><span>Every finding points to a record.</span></li><li><b>Hand off a cleaner plan</b><span>Export, then verify on staging.</span></li></ol></aside></section>
  <div className="boundary"><b>Plan review only.</b> No URLs are fetched. Live status codes, destination relevance and SEO outcomes still need separate verification. Use synthetic or public URLs only.</div>
  <div className="workspace"><section className="panel input-panel"><div className="panel-head"><div><p className="eyebrow">01 / INPUT</p><h2>Your proposed map</h2></div><button className="secondary" disabled={busy} onClick={()=>{setCsv(sample);setInventory(sampleInventory);invalidate();setNotice('Loaded a synthetic example with deliberate issues.');}}>Load example</button></div>
   <form onSubmit={submit}><label htmlFor="csv">Redirect CSV</label><p className="hint">Headers: <code>old_url,new_url,status</code>. Status is optional; default 301. Absolute HTTP(S) URLs. 301 and 308 only.</p><textarea id="csv" disabled={busy} required spellCheck={false} value={csv} onChange={e=>{setCsv(e.target.value);invalidate();}} placeholder={'old_url,new_url,status\nhttps://example.com/old,https://example.com/new,301'} rows={12}/><label className="file-label">Or select a CSV file <input type="file" disabled={busy} accept=".csv,text/csv" onChange={e=>void loadFile(e.target.files?.[0])}/></label>
   <details><summary>Check inventory coverage <span>optional</span></summary><label htmlFor="inventory">Old URL inventory, one URL per line</label><textarea id="inventory" disabled={busy} rows={5} spellCheck={false} value={inventory} onChange={e=>{setInventory(e.target.value);invalidate();}} placeholder="https://example.com/old-page"/><p className="hint">An uncovered URL may remain unchanged or be intentionally removed. You make that decision.</p></details>
   <div className="form-actions"><button disabled={busy}>{busy?'Working…':'Review redirect map →'}</button><button type="button" className="text-button" onClick={clear} disabled={busy}>Clear inputs</button></div><p className="hint">{paid?'Test pass: up to 5,000 mappings per run.':'Free: up to 100 mappings, full results and exports.'} Inputs are processed in memory on our API; they are not stored there.</p></form>
  </section><aside className="panel result-panel" aria-live="polite"><div className="panel-head"><div><p className="eyebrow">02 / REVIEW</p><h2>{report?'Your preflight report':'Know what to fix next'}</h2></div>{report&&<span className={report.summary.errors?'result-badge danger':'result-badge'}>{report.summary.errors?'Needs attention':'Review ready'}</span>}</div>
   {error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
   {!report?<div className="empty"><span className="empty-icon">↳</span><h3>{busy?'Checking your map…':'A clear handoff starts here.'}</h3><p>Load the example to see conflicts, redirect cycles, duplicate records and an inventory gap.</p><ul><li>Conflicting destinations for one source</li><li>Self redirects, cycles and chains</li><li>Repeated mappings and unmapped URLs</li></ul></div>:<><div className="stats"><div><b>{report.summary.inputRows}</b><span>mappings</span></div><div><b>{report.summary.errors}</b><span>blocking findings</span></div><div><b>{report.summary.warnings}</b><span>review findings</span></div></div><label htmlFor="filter">Show findings</label><select id="filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All findings</option><option value="error">Blocking findings</option><option value="warning">Review findings</option></select><div className="issues">{visible.length?visible.slice(0,100).map((i,n)=><article className="issue" key={n}><div><span className={i.severity==='error'?'severity error':'severity'}>{i.severity==='error'?'BLOCKING':'REVIEW'}</span><span className="row-number">{i.code.includes('INVENTORY')||i.code==='UNMAPPED'?'Inventory line':'Map record'} {i.row}</span></div><b>{i.code.replaceAll('_',' ')}</b><code>{i.oldUrl}</code><p>{i.message}</p></article>):<p className="notice">No findings in this view. Live verification is still required.</p>}{visible.length>100&&<p>Showing first 100 findings. Download the complete issue CSV below.</p>}</div><div className="exports"><button className="secondary" onClick={()=>download('redirect-preflight-issues.csv',report.issuesCsv)}>Download all findings</button><label className="check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the warnings and understand the offline limitations.</label><button disabled={!reviewed||!report.summary.exportRows} onClick={()=>download('redirect-preflight-reviewed-map.csv',report.reviewedCsv)}>Export {report.summary.exportRows} nonblocking mappings</button><p className="hint">Conflicting, invalid and cyclic sources, including paths into them, are omitted. Duplicate sources appear once. Chains remain for your review.</p></div></>}
  </aside></div>
  <section className="pricing"><div><p className="eyebrow">ONE MIGRATION. ROOM TO ITERATE.</p><h2>A project pass, when you need more.</h2><p>100 mappings free. A <b>$19 USD one-time pass</b> unlocks up to 5,000 mappings per run for 30 days in this browser. No renewal. Pricing is an experiment.</p>{paid&&<p className="notice">Test pass active until {new Date(expiry).toLocaleDateString()}. No real money was charged.</p>}</div><div className="purchase"><label className="check"><input type="checkbox" checked={saveDraft} onChange={e=>setSaveDraft(e.target.checked)}/>Keep these inputs in this tab for checkout return.</label><button onClick={()=>void checkout()} disabled={busy||paid||!billing}>{paid?'Test pass active':billing?'Try $19 test checkout →':'Test checkout unavailable'}</button><p className="hint">Stripe sandbox only. Use test details. A pass is bound to this browser; clearing cookies loses demo access. Full/partial refunds and disputes disable it.</p></div></section>
  <footer><span>Redirect Preflight · Nex2i · Validation demo<br/>Literal URL maps only. Founder review pending.</span><a href="https://github.com/Nex2i/redirect-preflight">Source & review checklist ↗</a>{telemetryAvailable&&<div>{consent==='unset'?<><span>Allow anonymous usage analytics?</span><button className="secondary" onClick={()=>{setAnalyticsConsent(true);setConsent('granted');}}>Allow</button><button className="secondary" onClick={()=>{setAnalyticsConsent(false);setConsent('denied');}}>Decline</button></>:<button className="secondary" onClick={()=>{const grant=consent!=='granted';setAnalyticsConsent(grant);setConsent(grant?'granted':'denied');}}>{consent==='granted'?'Disable analytics':'Enable analytics'}</button>}</div>}</footer>
 </main>;
}

