import {test} from 'node:test';import assert from 'node:assert/strict';import{analyze,parseCsv}from './analyze.js';
const head='old_url,new_url,status\n';
test('detects conflicts duplicates loops chains and missing inventory; export excludes all blocked sources',()=>{const r=analyze({csv:head+'https://example.com/a,https://example.com/b,301\nhttps://example.com/b,https://example.com/a,301\nhttps://example.com/c,https://example.com/d,301\nhttps://example.com/c,https://example.com/e,301\nhttps://example.com/x,https://example.com/y,301\nhttps://example.com/x,https://example.com/y,301\nhttps://example.com/q,https://example.com/x,301\nhttps://example.com/z,https://example.com/a,301',inventory:'https://example.com/missing'});for(const c of['LOOP','CONFLICT','DUPLICATE','CHAIN','UNMAPPED','BLOCKED_TARGET'])assert(r.issues.some(i=>i.code===c),c);assert.equal(r.summary.exportRows,2);assert(!r.reviewedCsv.includes('https://example.com/z'));});
test('self redirect, unsafe URL and status rejected at their rows',()=>{const r=analyze({csv:head+'https://example.com/a,https://example.com/a,301\nhttps://example.com/b,javascript:alert(1),301\nhttps://example.com/c,https://example.com/d,302'});assert.deepEqual(r.issues.map(i=>i.code).sort(),['INVALID_STATUS','INVALID_URL','SELF_REDIRECT']);assert.equal(r.summary.exportRows,0);});
test('CSV quoted commas BOM CRLF and literal quotes; malformed structures fail',()=>{assert.deepEqual(parseCsv('\ufeffa,b\r\n"x,y","z""q"\r\n'),[['a','b'],['x,y','z"q']]);assert.throws(()=>parseCsv('a,b\n"x,y'));assert.throws(()=>parseCsv('a,b\n"x"z,y'));assert.throws(()=>analyze({csv:'x,y\na,b'}));});
test('free limit and paid maximum; query and path case stay distinct',()=>{const many=head+Array.from({length:101},(_,i)=>`https://example.com/${i},https://new.example.com/${i},301`).join('\n');assert.throws(()=>analyze({csv:many}),/Limit: 100/);assert.equal(analyze({csv:many},5000).summary.inputRows,101);const r=analyze({csv:head+'https://example.com/A?q=1,https://example.com/a?q=2,301'});assert.equal(r.summary.errors,0);assert(r.reviewedCsv.includes('/A?q=1'));});
test('same loop source appearing twice never exports',()=>{const r=analyze({csv:head+'https://example.com/a,https://example.com/b,301\nhttps://example.com/a,https://example.com/b,301\nhttps://example.com/b,https://example.com/a,301'});assert.equal(r.summary.exportRows,0);});
test('5000 rows complete and repeat deterministically',()=>{const many=head+Array.from({length:5000},(_,i)=>`https://example.com/${i},https://new.example.com/${i},301`).join('\n');const r=analyze({csv:many},5000);assert.equal(r.summary.exportRows,5000);assert.deepEqual(r,analyze({csv:many},5000));});
test('inventory line numbers preserve blank lines and over-limit runs fail',()=>{const r=analyze({csv:head+'https://example.com/a,https://example.com/b,301',inventory:'\n\nhttps://example.com/missing'});assert.equal(r.issues.find(x=>x.code==='UNMAPPED')?.row,3);const many=head+Array.from({length:5001},(_,i)=>`https://example.com/${i},https://new.example.com/${i},301`).join('\n');assert.throws(()=>analyze({csv:many},5000),/Limit: 5000/);});
